### ISSUE TITLE
Rank mismatch ftg_get_bounds

### ISSUE THREAD

**Issue by phmarti** [fortesg/fortrantestgenerator#10]
HI,

I'm trying to generate a test for part of ICON (ECHAM mo_surface.f90, update_surface routine). The test generated by FTG contains a call to ftg_get_bounds:

ftg_bounds = ftg_get_bounds("mo_mpi_phy_config__mpi_phy_config")

But ftg_bounds is defined as 

INTEGER, DIMENSION(4,2) :: ftg_bounds

while ftg_get_bounds returns a rank one array of dimension 8, leading to a compilation error due to the mismatch in ranks. 

Regards,
Philippe

**Comment by phmarti** [comment]
It's actually more than just a rank mismatch. The ordering of the data inside the ftg_bounds is different between serialbox-ftg and serialbox2:

serialbox-ftg: imin, jmin, ..., imax, jmax
serialbox2: imin, imax, jmin, jmax, ...

I edited the icon replay template and it seems to work.

**Comment by chovyy** [comment]
Dear @phmarti,

I'm very sorry, that I never have answered your request. Actually, I have seen it for the first time. I was thinking, that I will be notified via email for every issue automatically, but it turns out that this is not the case.

I guess, this bug was fixed in the meantime anyway, so I will close this issue.

Cheers, Christian
