### ISSUE TITLE
ftg_velocity_tendencies_capture_input put inside #ifdef...#endif at end of subroutine declaration part 

### ISSUE THREAD

**Issue by vectorflux** [fortesg/fortrantestgenerator#11]
We have the following #ifdef at the very end of the subroutine velocity_tendencies to be captured:

#ifdef _OPENACC
    REAL(wp), DIMENSION(:,:,:),   POINTER  :: vn_tmp, w_tmp
    REAL(vp), DIMENSION(:,:,:),   POINTER  :: vt_tmp, vn_ie_tmp
    REAL(vp), DIMENSION(:,:,:),   POINTER  :: w_concorr_c_tmp
    REAL(vp), DIMENSION(:,:,:,:), POINTER  :: ddt_vn_adv_tmp
    REAL(vp), DIMENSION(:,:,:,:), POINTER  :: ddt_w_adv_tmp
#endif
    !--------------------------------------------------------------------------

    IF (timers_level > 5) CALL timer_start(timer_solve_nh_veltend)

FTG puts the ftg_velocity_tendencies_capture_input inside the #ifdef  ... #endif, namely
#ifdef _OPENACC
    REAL(wp), DIMENSION(:,:,:),   POINTER  :: vn_tmp, w_tmp
    REAL(vp), DIMENSION(:,:,:),   POINTER  :: vt_tmp, vn_ie_tmp
    REAL(vp), DIMENSION(:,:,:),   POINTER  :: w_concorr_c_tmp
    REAL(vp), DIMENSION(:,:,:,:), POINTER  :: ddt_vn_adv_tmp
    REAL(vp), DIMENSION(:,:,:,:), POINTER  :: ddt_w_adv_tmp

  ! ================= BEGIN FORTRAN TEST GENERATOR (FTG) =======================

  ftg_velocity_tendencies_round = ftg_velocity_tendencies_round + 1
  CALL ftg_velocity_tendencies_capture_input(p_prog, p_patch, p_int, p_metrics, p_diag, z_w_concorr_me, z_kin_hor_e, z_vt_ie, &
  &  ntnd, istep, lvn_only, dtime)

#endif

This is means the that it is not going to work for CPU-only.  The fix is obvious.

There is a wider philosophical issue here.  In my mind, FTG should be applied not to the icon/src directory (recursively), but rather to the pre-processed source in: build/x86_64-unknown-linux-gnu/src (flat file structure, not recursive).  Why?  If FTG alters source in src, it will be flagged as differences by GIT.  This is very confusing for the developer.  The preprocessed files also remove all the #ifdefs and are thus simpler than the original.  And obviously this will avoid the bug mentioned here.

**Comment by chovyy** [comment]
Dear @vectorflux,

I'm very sorry, that I haven't answered your request yet. Actually, I have seen it now for the first time. I was thinking, that I will be notified via email for every issue automatically, but it turns out that this is not the case.

Some thoughts on your issue: 

1. FTG was never thought as fully automatic and the generated code is supposed to be edited by the developer. Of course, it should be working as well as possible on its own, but if there is something that leads to an error that can be fixed as easy as in this situation, I think it's fine. But of course, such errors are not always that obvious.

2. FTG normally acts as if there is no such thing as a preprocessor. In my experience, in most cases it works anyway, or resulting errors can be fixed manually very easily. 

3. Regarding git, I would always create a new branch when start working with FTG.

4. You can actually let FTG modify the pre-processed sources. It's up to your configuration. 
Just set `SOURCE_DIRS = ASSEMBLER_DIRS` and `SOURCE_FILES_PREPROCESSED = True` in your `config_fortrancallgraph.py` and don't set `MODIFY_SOURCE_DIRS` in `config_fortrantestgenerator.py`.

**Comment by chovyy** [comment]
#12 is duplicate. We'll continue our discussion there...

**Comment by vectorflux** [comment]
Thanks for the tips.  As  mentioned, it is no big deal, now that I have learned about the risk of this happening...
