### ISSUE TITLE
[Question] What is the difference with KGen? 

### ISSUE THREAD

**Issue by clementval** [fortesg/fortrantestgenerator#3]
@chovyy I heard about your tool from Will Sawyer at CSCS. I was wondering what is the difference with KGEN developed by NCAR. Do you know this tool? Did you have a look at it? For me, it looks really similar.

https://github.com/NCAR/KGen

**Comment by chovyy** [comment]
Hi @clementval,

you  are right, KGEN is quite similar to the FortranTestGenerator. Both were started independently, but since around 1,5 years we (me and the main developer of KGEN) are in touch and had a lot of fruitful discussions.

FTG uses a very different approach to the source code analysis than KGEN.

Further KGEN is more automatized, but therefore the user of FTG can better control the process, either by editing the templates that are used for generating the capture and/or the replay code or by editing the generated code itself.

Cheers, Christian
